### ISSUE TITLE
Dual licencse under Apache 2.0 and MIT

### ISSUE THREAD

**Issue by badcodecat** [appybara13/pxo#1]
Context: I am in the process of developing a plugin to add PXO file support to the Bevy game engine. Notably, Bevy plugins are typically dual-licensed under the Apache 2.0 and MIT licenses, like the main bevy project. This dual licensing approach has several advantages, as discussed in this [Bevy issue](https://github.com/bevyengine/bevy/issues/2373). 

It would be nice to be able to do the same for the [PXO Plugin](https://github.com/badcodecat/bevy_pxo) I'm working on.
Thanks for your consideration.

**Comment by appybara13** [comment]
Thanks @badcodecat for your contribution with #3, I'll make the request license change now and then publish.
